### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by furudean** [tolbertam/hyper-font-ligatures#1]
Cannot get the plugin to work with [FiraCode](https://github.com/tonsky/FiraCode). No ligatures are being rendered in the editor.

![screenshot 2018-10-04 at 09 08 28](https://user-images.githubusercontent.com/31383109/46458132-16c7c900-c7b5-11e8-98b2-a27e2d22ee26.png)

**Comment by furudean** [comment]
Sorry - did not see the disclaimer.

**Comment by tolbertam** [comment]
No problem!  Hopefully there will be a hyper release with xterm 3.7 soon.  I've been using a development version and ligatures work really well with 3.6
