### ISSUE TITLE
Hyper shows error on split window

### ISSUE THREAD

**Issue by neet** [tolbertam/hyper-font-ligatures#2]
Hyper 2.1.0 with ligature support is still not in a stable version so I tried it with [`2.1.0-canary.3`](https://github.com/zeit/hyper/releases/tag/2.1.0-canary.3). And I've got an error on split window with `⌘D`.

<img width="338" alt="2018-12-11 13 51 49" src="https://user-images.githubusercontent.com/19276905/49779195-fd5e7280-fd4b-11e8-97de-70d32421fbe5.png">

Although it shows an error, the ligatures seems to be working
<img width="1004" alt="2018-12-11 13 58 40" src="https://user-images.githubusercontent.com/19276905/49779340-e4a28c80-fd4c-11e8-8957-b9e1204ce1ce.png">

#### Versions
Hyper: 2.1.0-canary.3
hyper-font-ligatures: 0.0.3
OS: macOS mojave 10.14.2 Beta

#### Chrome developer tools
```
TypeError: Cannot read property 'term' of null
    at Object.onDecorated (/Users/nucx/.hyper_plugins/node_modules/hyper-font-ligatures/index.js:15)
    at Object.onRef (bundle.js:1)
    at c (bundle.js:1)
    at d (bundle.js:1)
    at g (bundle.js:1)
    at commitDeletion (bundle.js:1)
    at b (bundle.js:1)
    at m (bundle.js:1)
    at w (bundle.js:1)
    at z (bundle.js:1)
```

#### ~/.hyper.js
```js
module.exports = {
  localPlugins: [
  ],

  plugins: [
    'hyper-font-ligatures',
  ],

  config: {
    updateChannel: 'canary',
    fontFamily: 'FuraCode Nerd Font',
    shellArgs: ['--login'],
  },
};
```

**Comment by tolbertam** [comment]
This looks easy to fix, for some reason, the method is invoked with null...in this case we can just return as there is nothing to decorate...will fix

**Comment by tolbertam** [comment]
I just pushed 0.0.4 and I no longer encounter the issue when splitting windows.  Could you please try installing the latest version and let me know if it works?

**Comment by neet** [comment]
@tolbertam Thank you for your quick response! I've just updated to `0.0.4` and it  works fine 👍 

<img width="927" alt="2018-12-12 16 32 38" src="https://user-images.githubusercontent.com/19276905/49853795-a6c86580-fe2b-11e8-82e7-5bf85c2874bc.png">

**Comment by tolbertam** [comment]
@neet, thank you for reporting this issue and verifying the fix, glad it's working! :tada:
