### ISSUE TITLE
"hyper-font-ligatures" failed to load in the renderer process.

### ISSUE THREAD

**Issue by boyedarat** [tolbertam/hyper-font-ligatures#5]
I get the following error when loading Hyper or doing a View->Full Reload:
![image](https://user-images.githubusercontent.com/22816484/50967738-f88c0a80-1513-11e9-9bf5-de8512f6aaa8.png)

Here is the error log from Developer tools:

```
bundle.js:1 (re)loading renderer plugins
bundle.js:1 Plugin hyper-font-ligatures (0.0.6) loaded.
bundle.js:1 No package.json found in C:\Users\me\.hyper_plugins\local\hyper-font-ligatures
M @ bundle.js:1
bundle.js:1 [Notification] Plugin load error: "hyper-font-ligatures" failed to load in the renderer process. Check Developer Tools for details.
bundle.js:1 Error: Cannot find module 'C:\Users\me\.hyper_plugins\local\hyper-font-ligatures'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\me\AppData\Local\hyper\app-2.1.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Function.f._load (file:///C:/Users/me/AppData/Local/hyper/app-2.1.1/resources/app.asar/renderer/bundle.js:1:5102)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at O.e.plugins.concat.filter.map (file:///C:/Users/me/AppData/Local/hyper/app-2.1.1/resources/app.asar/renderer/bundle.js:1:6159)
    at Array.map (native)
    at O (file:///C:/Users/me/AppData/Local/hyper/app-2.1.1/resources/app.asar/renderer/bundle.js:1:6110)
    at Object.<anonymous> (file:///C:/Users/me/AppData/Local/hyper/app-2.1.1/resources/app.asar/renderer/bundle.js:1:7825)
t.a @ bundle.js:1
index.html:35 total init time 851.0049999999999
```

However the plug-in seems to work fine:
![image](https://user-images.githubusercontent.com/22816484/50967990-b911ee00-1514-11e9-9950-3f466a15080c.png)

Platform details:
![image](https://user-images.githubusercontent.com/22816484/50968024-d2b33580-1514-11e9-9739-0b9473b48642.png)

OS: Windows 10 Pro 1809

**Comment by tolbertam** [comment]
Hi @boyedarat, thanks for the bug report!  I confess I haven't tried this package on any platform but linux, but I do have a windows machine handy at home.

The error on the other hand looks odd, like maybe I messed up when I deployed the latest version.  I'll find out tonight when I can give it a try.

**Comment by tolbertam** [comment]
Apologies for the delay here.  I finally got around to loading up my windows machine and I didn't run into the same issue using Hyper 2.1.2 on Windows 10 Home:

```
(re)loading renderer plugins
bundle.js:1 Plugin hyper-font-ligatures (0.0.6) loaded.
index.html:35 total init time 433.85
```

I noticed that the file path attempted to be loaded in your case was: `C:\Users\me\.hyper_plugins\local\hyper-font-ligatures`

However for me, the plugin is installed in `C:\Users\<myuser>\.hyper_plugins\node_modules\hyper-font-ligatures` and a package.json file is present.  Can you give me more information with regards to how you installed the plugin?  Did you use the conventional `hyper i <pluginname>` or some other approach?

**Comment by boyedarat** [comment]
Seems like it was a bug on hyper itself. Looks like it is fixed now.

**Comment by tolbertam** [comment]
:+1: thank you for following up @boyedarat.  Glad to hear it's working for you now!
