### ISSUE TITLE
Uncaught TypeError: Cannot read property 'en' of undefined

### ISSUE THREAD

**Issue by victorloux** [tolbertam/hyper-font-ligatures#6]
Hi, I'm getting the following error using Hyper 2.1.1 on macOS. 

The terminal loads as normal when it starts:

![Screenshot 2019-04-03 at 13 08 34](https://user-images.githubusercontent.com/1223641/55477690-a1c53700-5611-11e9-85bd-1fa948651e45.png)

However as soon as I type a character, it hangs, doesn't write anything and renders the prompt incorrectly:

![Screenshot 2019-04-03 at 13 08 39](https://user-images.githubusercontent.com/1223641/55477691-a1c53700-5611-11e9-9e77-8ce11047dfdb.png)

In the devtools console I get this error:

```
index.ts:75
Uncaught TypeError: Cannot read property 'en' of undefined
    at Object.name (extract.ts:35)
    at getMetadata (index.ts:162)
    at parallelize (index.ts:97)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```

The first `index.ts` is in the package xterm-addon-ligatures; `extract.ts` is in font-finder. From the code I can't figure out where that `'en'` is from, it looks like it cannot load the font but I've reset the font to a default one (system, non-ligatures, no fallbacks) and it gives the same thing. Looks like the plugins can't load fonts at all, but I can't figure out why, and there's no similar issue on the relevant module repositories.

I've tried resetting settings to anything else, disabling all other plugins, but it doesn't fix it. The font I was trying to use is FuraCode Nerd but again, that doesn't seem to be the issue as it still happens with any other font.

**Comment by tolbertam** [comment]
Not quite sure what to make of it either

https://github.com/princjef/font-finder/blob/b1f41fa1d62c664e4c2645ede36a86c56996d201/src/extract.ts#L35

It looks like maybe the font is properly referenced but for whatever reason `fontFamily` for that particular (or any font) is unresolved?

How are you declaring your fonts in your hyper configuration?  Here is what my config looks like:

```javascript
module.exports = {
  config: {
    //...
    fontFamily: '"Fira Code", "Iosevka", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    //...
  }
}
```

Can look into this later tonight.  I wonder if this could also be an OS X issue, only because I've never tried this on that platform.

**Comment by victorloux** [comment]
I thought that as well, but it looks normal and I've tried changing this to any other font - Hyper will resolve whatever the first font is and use that, but even when it's a system default, the plugin will throw this. It could well be a macOS issue, but it looks strange that I'm the first to get that issue with the other plugins too.

(I just realised `'en'` is what the `language` property resolves to… duh!)

My full config line is:

```
    fontFamily: '"FuraCode Nerd Font", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
```

**Comment by tolbertam** [comment]
Thanks for sharing your config, that looks right to me.

> It could well be a macOS issue, but it looks strange that I'm the first to get that issue with the other plugins too.

Yeah I agree, it seems likely if it was a macOS thing that its likely this would have come up earlier.

I'll look into this some more when I get a chance this evening.  I think debugging in that code when it works might give me some insight into why it may not work in other cases.

**Comment by tolbertam** [comment]
apologies for not following up, was working late last night.  I think i'll get some time to look at this today, will follow up with what I find.

**Comment by tolbertam** [comment]
Sorry for the late follow up, what a couple of weeks it has been!  Hope all is well.

So I did a little debugging and realized this evaluation is done for every installed font, not just the fonts you specify in `fontFamily`: 

https://github.com/princjef/font-finder/blob/b1f41fa1d62c664e4c2645ede36a86c56996d201/src/index.ts#L90-L107

This seems consistent with your explanation that it happens with any font you specify.  If there is one font installed that for whatever reason lacks both `preferredFamily` and `fontFamily`, the plugin will bail

```
    const family = fontData.names.preferredFamily && fontData.names.preferredFamily[language]
        ? fontData.names.preferredFamily[language]
        : fontData.names.fontFamily[language];
```

as font-finder will throw any language level errors:

```
                if (['TypeError', 'SyntaxError', 'ReferenceError', 'RangeError', 'AssertionError'].includes(e.name)) {
                    throw e;
}
```

If you have the time, I would appreciate if you could help me get an idea of what font(s) lack these attributes, and what attributes they do have.  

To test this out you could add the following at line 86 of ~/.hyper_plugins/node_modules/font-finder/dist/index.js:

```javascript
function getMetadata(path, fontData, language) {
    console.log('Getting metadata for', path, ' fontData: ', fontData); // <---
```

You could then load up hyper with the hyper-font-ligatures enabled, and go to `Menu -> View -> Developer Tools` navigate to console, and observe the attributes of the fontData:

![Screenshot from 2019-04-20 14-47-33](https://user-images.githubusercontent.com/6889771/56461616-82e9d300-637b-11e9-997c-18f8e2b45b5b.png)

My guess is either there is some kind of corrupt font installed, or font-finder needs to accommodate for possibly another field name (a la `preferredFamily` and `fontFamily`).  In the former case, maybe font-finder could be updated to skip fonts that lack these attributes, and in the latter case it could be updated to look for another field as well.  In any case I can try to contribute a patch.

**Comment by tolbertam** [comment]
Just following up, I got my hands on a Mac and can confirm that things can work on a mac, as I was not able to reproduce this issue.  So I think the issue is that there is a font that `font-finder` isn't able to handle, if we can find out what font that is, I can reproduce it and propose a fix for that library.

**Comment by victorloux** [comment]
Thanks a lot for looking into this, apologies I've not had time to reply earlier — I'll try to see if I can hunt down the font that breaks it.

**Comment by victorloux** [comment]
Found the culprit - it was a font which had neither a `fontFamily` or `preferredFamily` key at all under `name`.
In font management tools it is listed as its `fullName` key ("PFDinMono-Italic"), and details its full name as "Not Available".

![screenshot of FontExplorer showing the name as Not Available](https://user-images.githubusercontent.com/1223641/56896595-0b572a80-6a84-11e9-843e-e8096cdcc3ab.png)

I deactivated the font and the plugin worked instantly. I guess font-finder just needs to have a fallback if neither are available then.  
Thanks a lot for helping me track down the root of the issue! Let me know if I can do anything more to help — it's a commercial font so I don't think I can legally send you the file to test with, but happy to give you more info if you need.

**Comment by tolbertam** [comment]
Hi @victorloux.  Thanks for confirming that this was the case!  I agree that font-finder should fallback in this case (probably just by ignoring the font).  I'll open up a PR there to just that, thanks!

**Comment by alexpriest** [comment]
Just for the record, I ran into a similar problem today. Thanks for your help! It was slightly different for for me, but your guidance helped me figure it out:
- The culprit font was "Posterama" — lots of files, all with weird file names e.g. "0c404145-ea59-4df9-aa31-a3b67b7f2b9b.ttf"
- I _think_ each file had a proper name associated with it, so not entirely sure what was throwing the error.
- Deleting the files completely solved the issue immediately.

**Comment by xXGoziXx** [comment]
I ran into the exact same problem. 
`fontFamily: "'FuraCode Nerd Font','FuraCode Nerd Font Mono','Fira Code', Menlo, Monaco, 'Courier New', monospace"`
I don't know how to resolve this. I get this error when I set
`webGLRenderer: false`

Btw, I'm trying to use font-ligatures that's why I need webGLRenderer to be false for the 'hyper-font-ligatures' plugin to work.

**Comment by xXGoziXx** [comment]
Also this occurs regardless of what font I use...
