### ISSUE TITLE
[bug(?)] Does not seem to work

### ISSUE THREAD

**Issue by aadibajpai** [tolbertam/hyper-font-ligatures#7]
I'm on hyper 2.1.2

I've installed the plugin and trying it out with Fira Code but no ligatures :(

![image](https://user-images.githubusercontent.com/27063113/56428515-47003080-62dd-11e9-9533-a95f6036f790.png)

Let me know if I'm doing something wrong 😃

**Comment by tolbertam** [comment]
Hello, thank you for giving this plugin a try.

I speculate that maybe Fira Code is not being used, can you double check?  Some characters (`@` and `$`) look different than what I'm accustomed to seeing with Fira Code.

![Screenshot from 2019-04-20 13-52-52](https://user-images.githubusercontent.com/6889771/56461153-a1e46700-6373-11e9-8f47-b29d7223c839.png)

Can you share the values of your `font` prefixed settings in ~/.hyper.js (or wherever that file lives on windows)?  Here's how I have it configured:

```json
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: '"Fira Code", "Iosevka", Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // default font weight: 'normal' or 'bold'
    fontWeight: 'normal',

    // font weight for bold characters: 'normal' or 'bold'
    fontWeightBold: 'bold',
```

It might also be valuable to check Developer Tools (Menu > View > Developer Tools) and see if any errors show up in console.

**Comment by tolbertam** [comment]
Was just playing around with the `fontFamily` option a bit and I noticed that if I simply had it configured as:

```json
fontFamily: '"Fira Code"',
```

That while the font loaded, ligatures did not.  I suspect maybe I'm missing some style of the font installed.  If I add `Consolas` as a fallback, like so:

```json
fontFamily: '"Fira Code", Consolas',
```

Everything works.   Perhaps this is the issue you are encountering as well?  Could you check your configured fontFamily and add a font as a fallback and see if that helps?

**Comment by tolbertam** [comment]
Just tried this on my windows box and

```
fontFamily: 'Fira Code',
```

Worked for me, but there might be factors here beyond operating system.

**Comment by aadibajpai** [comment]
Right on, I dropped the ball here, since Fira Code was available off the bat in my JetBrains IDEs, I never actually installed Fira Code. Did that and it works!

![image](https://user-images.githubusercontent.com/27063113/56462736-e6a8e600-63e5-11e9-9937-408f123716ce.png)

**Comment by tolbertam** [comment]
Thanks for following up, glad to hear you got working! :beers:
